import type { GridTemplate } from '../types'

type CellSpec = { col: number; row: number; colSpan: number; rowSpan: number }

interface GeometryDef {
  key: string
  label: string
  count: number
  cols: number
  rows: number
  cells: CellSpec[]
}

/**
 * Hand-picked grid layouts (geometries). Most tile their cols x rows unit
 * grid exactly (no gaps) — sum of colSpan*rowSpan per row == cols. A couple
 * of small-count layouts (grid-2-diagonal, grid-3-corner) deliberately don't:
 * they leave part of the grid empty on purpose, as a designed accent rather
 * than a full tiling.
 *
 * Every photo count (2-9) gets 4 layouts. The cell "shape" (rect / rounded)
 * is a separate, orthogonal choice made in the UI, not baked into these.
 */
const GEOMETRIES: GeometryDef[] = [
  // ---- 2 photos ----
  {
    key: 'grid-2-normal',
    label: '2 fotos',
    count: 2,
    cols: 2,
    rows: 1,
    cells: [
      { col: 0, row: 0, colSpan: 1, rowSpan: 1 },
      { col: 1, row: 0, colSpan: 1, rowSpan: 1 },
    ],
  },
  {
    // 8:5 ~= golden ratio (0.615/0.385) — a subtler, less "cut in a blender"
    // asymmetry than the old plain 3:2 (0.6/0.4) split.
    key: 'grid-2-big-left',
    label: '2 fotos · grande y chica',
    count: 2,
    cols: 13,
    rows: 1,
    cells: [
      { col: 0, row: 0, colSpan: 8, rowSpan: 1 },
      { col: 8, row: 0, colSpan: 5, rowSpan: 1 },
    ],
  },
  {
    key: 'grid-2-big-right',
    label: '2 fotos · chica y grande',
    count: 2,
    cols: 13,
    rows: 1,
    cells: [
      { col: 0, row: 0, colSpan: 5, rowSpan: 1 },
      { col: 5, row: 0, colSpan: 8, rowSpan: 1 },
    ],
  },
  {
    // Two square cells on the diagonal of a 2x2 grid, the other two units left
    // as deliberate negative space — reads as a designed accent rather than a
    // leftover gap.
    key: 'grid-2-diagonal',
    label: '2 fotos · acento diagonal',
    count: 2,
    cols: 2,
    rows: 2,
    cells: [
      { col: 0, row: 0, colSpan: 1, rowSpan: 1 },
      { col: 1, row: 1, colSpan: 1, rowSpan: 1 },
    ],
  },

  {
    // Deliberate negative space: top-left is intentionally left empty.
    key: 'grid-2-big-right-gap',
    label: '2 fotos · grande + espacio negativo',
    count: 2,
    cols: 3,
    rows: 3,
    cells: [
      { col: 1, row: 0, colSpan: 2, rowSpan: 3 },
      { col: 0, row: 2, colSpan: 1, rowSpan: 1 },
    ],
  },
  {
    // Deliberate negative space: a small notch at top-left is intentionally left empty.
    key: 'grid-2-side-notch',
    label: '2 fotos · vertical con muesca',
    count: 2,
    cols: 2,
    rows: 5,
    cells: [
      { col: 0, row: 1, colSpan: 1, rowSpan: 4 },
      { col: 1, row: 0, colSpan: 1, rowSpan: 5 },
    ],
  },
  {
    // 60/40 horizontal split — a ratio between the plain 50/50 (normal) and
    // the ~61.5/38.5 golden-ratio split (big-left/big-right).
    key: 'grid-2-split-60-40',
    label: '2 fotos · 60/40',
    count: 2,
    cols: 5,
    rows: 1,
    cells: [
      { col: 0, row: 0, colSpan: 3, rowSpan: 1 },
      { col: 3, row: 0, colSpan: 2, rowSpan: 1 },
    ],
  },
  {
    // 70/30 horizontal split — a sharper asymmetry than the golden-ratio and
    // 60/40 splits.
    key: 'grid-2-small-big-70-30',
    label: '2 fotos · chica y grande (70/30)',
    count: 2,
    cols: 10,
    rows: 1,
    cells: [
      { col: 0, row: 0, colSpan: 3, rowSpan: 1 },
      { col: 3, row: 0, colSpan: 7, rowSpan: 1 },
    ],
  },
  {
    // Deliberate negative space: a big photo fills the left 3/5, the second
    // "floats" as a small square on the right with margin on every side.
    key: 'grid-2-floating',
    label: '2 fotos · foto flotante',
    count: 2,
    cols: 5,
    rows: 3,
    cells: [
      { col: 0, row: 0, colSpan: 3, rowSpan: 3 },
      { col: 4, row: 1, colSpan: 1, rowSpan: 1 },
    ],
  },

  // ---- 3 photos ----
  {
    key: 'grid-3-normal',
    label: '3 fotos',
    count: 3,
    cols: 3,
    rows: 1,
    cells: [
      { col: 0, row: 0, colSpan: 1, rowSpan: 1 },
      { col: 1, row: 0, colSpan: 1, rowSpan: 1 },
      { col: 2, row: 0, colSpan: 1, rowSpan: 1 },
    ],
  },
  {
    // 5:3 rows (62.5/37.5) instead of a flat 50/50 split.
    key: 'grid-3-big-top',
    label: '3 fotos · grande + 2',
    count: 3,
    cols: 2,
    rows: 8,
    cells: [
      { col: 0, row: 0, colSpan: 2, rowSpan: 5 },
      { col: 0, row: 5, colSpan: 1, rowSpan: 3 },
      { col: 1, row: 5, colSpan: 1, rowSpan: 3 },
    ],
  },
  {
    key: 'grid-3-big-bottom',
    label: '3 fotos · 2 + grande',
    count: 3,
    cols: 2,
    rows: 8,
    cells: [
      { col: 0, row: 0, colSpan: 1, rowSpan: 3 },
      { col: 1, row: 0, colSpan: 1, rowSpan: 3 },
      { col: 0, row: 3, colSpan: 2, rowSpan: 5 },
    ],
  },
  {
    // Three square cells filling an L in a 2x2 block, one corner left open —
    // a compact, deliberate accent, not a leftover gap.
    key: 'grid-3-corner',
    label: '3 fotos · esquina',
    count: 3,
    cols: 2,
    rows: 2,
    cells: [
      { col: 0, row: 0, colSpan: 1, rowSpan: 1 },
      { col: 1, row: 0, colSpan: 1, rowSpan: 1 },
      { col: 0, row: 1, colSpan: 1, rowSpan: 1 },
    ],
  },

  {
    key: 'grid-3-tall-right',
    label: '3 fotos · columna derecha alta',
    count: 3,
    cols: 2,
    rows: 2,
    cells: [
      { col: 0, row: 0, colSpan: 1, rowSpan: 1 },
      { col: 1, row: 0, colSpan: 1, rowSpan: 2 },
      { col: 0, row: 1, colSpan: 1, rowSpan: 1 },
    ],
  },
  {
    key: 'grid-3-band-top',
    label: '3 fotos · franja superior + 2',
    count: 3,
    cols: 2,
    rows: 2,
    cells: [
      { col: 0, row: 0, colSpan: 2, rowSpan: 1 },
      { col: 0, row: 1, colSpan: 1, rowSpan: 1 },
      { col: 1, row: 1, colSpan: 1, rowSpan: 1 },
    ],
  },
  {
    key: 'grid-3-stack-grow',
    label: '3 fotos · apiladas creciente',
    count: 3,
    cols: 1,
    rows: 6,
    cells: [
      { col: 0, row: 0, colSpan: 1, rowSpan: 1 },
      { col: 0, row: 1, colSpan: 1, rowSpan: 2 },
      { col: 0, row: 3, colSpan: 1, rowSpan: 3 },
    ],
  },
  {
    key: 'grid-3-strips-uneven',
    label: '3 fotos · tiras asimétricas',
    count: 3,
    cols: 9,
    rows: 1,
    cells: [
      { col: 0, row: 0, colSpan: 3, rowSpan: 1 },
      { col: 3, row: 0, colSpan: 2, rowSpan: 1 },
      { col: 5, row: 0, colSpan: 4, rowSpan: 1 },
    ],
  },
  {
    key: 'grid-3-side-stack',
    label: '3 fotos · panel + 2 apiladas',
    count: 3,
    cols: 9,
    rows: 9,
    cells: [
      { col: 0, row: 0, colSpan: 4, rowSpan: 9 },
      { col: 4, row: 0, colSpan: 5, rowSpan: 5 },
      { col: 4, row: 5, colSpan: 5, rowSpan: 4 },
    ],
  },
  {
    key: 'grid-3-block-column-band',
    label: '3 fotos · bloque + columna + franja',
    count: 3,
    cols: 3,
    rows: 3,
    cells: [
      { col: 0, row: 0, colSpan: 2, rowSpan: 2 },
      { col: 2, row: 0, colSpan: 1, rowSpan: 3 },
      { col: 0, row: 2, colSpan: 2, rowSpan: 1 },
    ],
  },
  {
    key: 'grid-3-thin-band-cols',
    label: '3 fotos · franja fina + 2 columnas',
    count: 3,
    cols: 5,
    rows: 10,
    cells: [
      { col: 0, row: 0, colSpan: 5, rowSpan: 3 },
      { col: 0, row: 3, colSpan: 3, rowSpan: 7 },
      { col: 3, row: 3, colSpan: 2, rowSpan: 7 },
    ],
  },
  {
    key: 'grid-3-stack-panel-right',
    label: '3 fotos · 2 apiladas + panel derecho',
    count: 3,
    cols: 9,
    rows: 9,
    cells: [
      { col: 0, row: 0, colSpan: 4, rowSpan: 6 },
      { col: 0, row: 6, colSpan: 4, rowSpan: 3 },
      { col: 4, row: 0, colSpan: 5, rowSpan: 9 },
    ],
  },

  // ---- 4 photos ----
  {
    key: 'grid-4-normal',
    label: '4 fotos',
    count: 4,
    cols: 2,
    rows: 2,
    cells: [
      { col: 0, row: 0, colSpan: 1, rowSpan: 1 },
      { col: 1, row: 0, colSpan: 1, rowSpan: 1 },
      { col: 0, row: 1, colSpan: 1, rowSpan: 1 },
      { col: 1, row: 1, colSpan: 1, rowSpan: 1 },
    ],
  },
  {
    key: 'grid-4-big-top',
    label: '4 fotos · grande + 3',
    count: 4,
    cols: 3,
    rows: 8,
    cells: [
      { col: 0, row: 0, colSpan: 3, rowSpan: 5 },
      { col: 0, row: 5, colSpan: 1, rowSpan: 3 },
      { col: 1, row: 5, colSpan: 1, rowSpan: 3 },
      { col: 2, row: 5, colSpan: 1, rowSpan: 3 },
    ],
  },
  {
    key: 'grid-4-big-bottom',
    label: '4 fotos · 3 + grande',
    count: 4,
    cols: 3,
    rows: 8,
    cells: [
      { col: 0, row: 0, colSpan: 1, rowSpan: 3 },
      { col: 1, row: 0, colSpan: 1, rowSpan: 3 },
      { col: 2, row: 0, colSpan: 1, rowSpan: 3 },
      { col: 0, row: 3, colSpan: 3, rowSpan: 5 },
    ],
  },
  {
    key: 'grid-4-row',
    label: '4 fotos · en fila',
    count: 4,
    cols: 4,
    rows: 1,
    cells: [
      { col: 0, row: 0, colSpan: 1, rowSpan: 1 },
      { col: 1, row: 0, colSpan: 1, rowSpan: 1 },
      { col: 2, row: 0, colSpan: 1, rowSpan: 1 },
      { col: 3, row: 0, colSpan: 1, rowSpan: 1 },
    ],
  },

  {
    key: 'grid-4-band-split',
    label: '4 fotos · franja + columna dividida',
    count: 4,
    cols: 2,
    rows: 3,
    cells: [
      { col: 0, row: 0, colSpan: 2, rowSpan: 1 },
      { col: 0, row: 1, colSpan: 1, rowSpan: 2 },
      { col: 1, row: 1, colSpan: 1, rowSpan: 1 },
      { col: 1, row: 2, colSpan: 1, rowSpan: 1 },
    ],
  },
  {
    key: 'grid-4-mixed-band',
    label: '4 fotos · mosaico + franja inferior',
    count: 4,
    cols: 2,
    rows: 4,
    cells: [
      { col: 0, row: 0, colSpan: 1, rowSpan: 1 },
      { col: 1, row: 0, colSpan: 1, rowSpan: 3 },
      { col: 0, row: 1, colSpan: 1, rowSpan: 2 },
      { col: 0, row: 3, colSpan: 2, rowSpan: 1 },
    ],
  },
  {
    key: 'grid-4-corner-bands',
    label: '4 fotos · esquina + 2 franjas',
    count: 4,
    cols: 3,
    rows: 3,
    cells: [
      { col: 0, row: 0, colSpan: 1, rowSpan: 1 },
      { col: 1, row: 0, colSpan: 2, rowSpan: 1 },
      { col: 0, row: 1, colSpan: 3, rowSpan: 1 },
      { col: 0, row: 2, colSpan: 3, rowSpan: 1 },
    ],
  },
  {
    key: 'grid-4-pinwheel-offset',
    label: '4 fotos · pinwheel asimétrico',
    count: 4,
    cols: 2,
    rows: 5,
    cells: [
      { col: 0, row: 0, colSpan: 1, rowSpan: 2 },
      { col: 1, row: 0, colSpan: 1, rowSpan: 3 },
      { col: 0, row: 2, colSpan: 1, rowSpan: 3 },
      { col: 1, row: 3, colSpan: 1, rowSpan: 2 },
    ],
  },
  {
    key: 'grid-4-banner-split',
    label: '4 fotos · banner + reparto',
    count: 4,
    cols: 8,
    rows: 8,
    cells: [
      { col: 0, row: 0, colSpan: 8, rowSpan: 3 },
      { col: 0, row: 3, colSpan: 3, rowSpan: 5 },
      { col: 3, row: 3, colSpan: 5, rowSpan: 2 },
      { col: 3, row: 5, colSpan: 5, rowSpan: 3 },
    ],
  },
  {
    key: 'grid-4-outer-tall',
    label: '4 fotos · columnas + centro dividido',
    count: 4,
    cols: 3,
    rows: 2,
    cells: [
      { col: 0, row: 0, colSpan: 1, rowSpan: 2 },
      { col: 1, row: 0, colSpan: 1, rowSpan: 1 },
      { col: 2, row: 0, colSpan: 1, rowSpan: 2 },
      { col: 1, row: 1, colSpan: 1, rowSpan: 1 },
    ],
  },
  {
    key: 'grid-4-pinwheel',
    label: '4 fotos · pinwheel simétrico',
    count: 4,
    cols: 3,
    rows: 2,
    cells: [
      { col: 0, row: 0, colSpan: 1, rowSpan: 1 },
      { col: 1, row: 0, colSpan: 2, rowSpan: 1 },
      { col: 0, row: 1, colSpan: 2, rowSpan: 1 },
      { col: 2, row: 1, colSpan: 1, rowSpan: 1 },
    ],
  },
  {
    key: 'grid-4-tall-stack-band',
    label: '4 fotos · alta + apiladas + franja',
    count: 4,
    cols: 2,
    rows: 8,
    cells: [
      { col: 0, row: 0, colSpan: 1, rowSpan: 5 },
      { col: 1, row: 0, colSpan: 1, rowSpan: 2 },
      { col: 1, row: 2, colSpan: 1, rowSpan: 3 },
      { col: 0, row: 5, colSpan: 2, rowSpan: 3 },
    ],
  },
  {
    key: 'grid-4-cols-band',
    label: '4 fotos · 3 columnas + franja',
    count: 4,
    cols: 3,
    rows: 8,
    cells: [
      { col: 0, row: 0, colSpan: 1, rowSpan: 5 },
      { col: 1, row: 0, colSpan: 1, rowSpan: 5 },
      { col: 2, row: 0, colSpan: 1, rowSpan: 5 },
      { col: 0, row: 5, colSpan: 3, rowSpan: 3 },
    ],
  },

  // ---- 5 photos ----
  {
    key: 'grid-5-normal-a',
    label: '5 fotos · 2 + 3',
    count: 5,
    cols: 6,
    rows: 2,
    cells: [
      { col: 0, row: 0, colSpan: 3, rowSpan: 1 },
      { col: 3, row: 0, colSpan: 3, rowSpan: 1 },
      { col: 0, row: 1, colSpan: 2, rowSpan: 1 },
      { col: 2, row: 1, colSpan: 2, rowSpan: 1 },
      { col: 4, row: 1, colSpan: 2, rowSpan: 1 },
    ],
  },
  {
    key: 'grid-5-normal-b',
    label: '5 fotos · 3 + 2',
    count: 5,
    cols: 6,
    rows: 2,
    cells: [
      { col: 0, row: 0, colSpan: 2, rowSpan: 1 },
      { col: 2, row: 0, colSpan: 2, rowSpan: 1 },
      { col: 4, row: 0, colSpan: 2, rowSpan: 1 },
      { col: 0, row: 1, colSpan: 3, rowSpan: 1 },
      { col: 3, row: 1, colSpan: 3, rowSpan: 1 },
    ],
  },
  {
    key: 'grid-5-tall-left',
    label: '5 fotos · lateral izq. + 4',
    count: 5,
    cols: 3,
    rows: 2,
    cells: [
      { col: 0, row: 0, colSpan: 1, rowSpan: 2 },
      { col: 1, row: 0, colSpan: 1, rowSpan: 1 },
      { col: 2, row: 0, colSpan: 1, rowSpan: 1 },
      { col: 1, row: 1, colSpan: 1, rowSpan: 1 },
      { col: 2, row: 1, colSpan: 1, rowSpan: 1 },
    ],
  },
  {
    key: 'grid-5-tall-right',
    label: '5 fotos · lateral der. + 4',
    count: 5,
    cols: 3,
    rows: 2,
    cells: [
      { col: 2, row: 0, colSpan: 1, rowSpan: 2 },
      { col: 0, row: 0, colSpan: 1, rowSpan: 1 },
      { col: 1, row: 0, colSpan: 1, rowSpan: 1 },
      { col: 0, row: 1, colSpan: 1, rowSpan: 1 },
      { col: 1, row: 1, colSpan: 1, rowSpan: 1 },
    ],
  },

  {
    key: 'grid-5-top-row-split',
    label: '5 fotos · 3 arriba + 2 abajo',
    count: 5,
    cols: 3,
    rows: 2,
    cells: [
      { col: 0, row: 0, colSpan: 1, rowSpan: 1 },
      { col: 1, row: 0, colSpan: 1, rowSpan: 1 },
      { col: 2, row: 0, colSpan: 1, rowSpan: 1 },
      { col: 0, row: 1, colSpan: 2, rowSpan: 1 },
      { col: 2, row: 1, colSpan: 1, rowSpan: 1 },
    ],
  },
  {
    key: 'grid-5-cols-asym',
    label: '5 fotos · columnas asimétricas',
    count: 5,
    cols: 2,
    rows: 20,
    cells: [
      { col: 0, row: 0, colSpan: 1, rowSpan: 13 },
      { col: 0, row: 13, colSpan: 1, rowSpan: 7 },
      { col: 1, row: 0, colSpan: 1, rowSpan: 6 },
      { col: 1, row: 6, colSpan: 1, rowSpan: 7 },
      { col: 1, row: 13, colSpan: 1, rowSpan: 7 },
    ],
  },
  {
    key: 'grid-5-strips-band',
    label: '5 fotos · 4 tiras + franja',
    count: 5,
    cols: 4,
    rows: 5,
    cells: [
      { col: 0, row: 0, colSpan: 1, rowSpan: 3 },
      { col: 1, row: 0, colSpan: 1, rowSpan: 3 },
      { col: 2, row: 0, colSpan: 1, rowSpan: 3 },
      { col: 3, row: 0, colSpan: 1, rowSpan: 3 },
      { col: 0, row: 3, colSpan: 4, rowSpan: 2 },
    ],
  },
  {
    key: 'grid-5-row-band-row',
    label: '5 fotos · fila + franja + fila',
    count: 5,
    cols: 2,
    rows: 3,
    cells: [
      { col: 0, row: 0, colSpan: 1, rowSpan: 1 },
      { col: 1, row: 0, colSpan: 1, rowSpan: 1 },
      { col: 0, row: 1, colSpan: 2, rowSpan: 1 },
      { col: 0, row: 2, colSpan: 1, rowSpan: 1 },
      { col: 1, row: 2, colSpan: 1, rowSpan: 1 },
    ],
  },
  {
    key: 'grid-5-split-panel',
    label: '5 fotos · columna dividida + panel',
    count: 5,
    cols: 10,
    rows: 3,
    cells: [
      { col: 0, row: 0, colSpan: 1, rowSpan: 1 },
      { col: 1, row: 0, colSpan: 4, rowSpan: 1 },
      { col: 0, row: 1, colSpan: 5, rowSpan: 1 },
      { col: 0, row: 2, colSpan: 5, rowSpan: 1 },
      { col: 5, row: 0, colSpan: 5, rowSpan: 3 },
    ],
  },
  {
    key: 'grid-5-hero-strip',
    label: '5 fotos · protagonista + tira inferior',
    count: 5,
    cols: 4,
    rows: 4,
    cells: [
      { col: 0, row: 0, colSpan: 4, rowSpan: 3 },
      { col: 0, row: 3, colSpan: 1, rowSpan: 1 },
      { col: 1, row: 3, colSpan: 1, rowSpan: 1 },
      { col: 2, row: 3, colSpan: 1, rowSpan: 1 },
      { col: 3, row: 3, colSpan: 1, rowSpan: 1 },
    ],
  },
  {
    key: 'grid-5-band-grid',
    label: '5 fotos · franja + cuadrícula 2x2',
    count: 5,
    cols: 4,
    rows: 3,
    cells: [
      { col: 0, row: 0, colSpan: 4, rowSpan: 1 },
      { col: 0, row: 1, colSpan: 2, rowSpan: 1 },
      { col: 2, row: 1, colSpan: 2, rowSpan: 1 },
      { col: 0, row: 2, colSpan: 2, rowSpan: 1 },
      { col: 2, row: 2, colSpan: 2, rowSpan: 1 },
    ],
  },
  {
    // Deliberate negative space: a thick L (top row + left column) leaves a
    // 2x2 block of the 3x3 grid intentionally empty at bottom-right.
    key: 'grid-5-corner-l',
    label: '5 fotos · esquina en L',
    count: 5,
    cols: 3,
    rows: 3,
    cells: [
      { col: 0, row: 0, colSpan: 1, rowSpan: 1 },
      { col: 1, row: 0, colSpan: 1, rowSpan: 1 },
      { col: 2, row: 0, colSpan: 1, rowSpan: 1 },
      { col: 0, row: 1, colSpan: 1, rowSpan: 1 },
      { col: 0, row: 2, colSpan: 1, rowSpan: 1 },
    ],
  },
  {
    key: 'grid-5-mixed-mosaic',
    label: '5 fotos · mosaico mixto',
    count: 5,
    cols: 5,
    rows: 2,
    cells: [
      { col: 0, row: 0, colSpan: 2, rowSpan: 2 },
      { col: 2, row: 0, colSpan: 3, rowSpan: 1 },
      { col: 2, row: 1, colSpan: 1, rowSpan: 1 },
      { col: 3, row: 1, colSpan: 1, rowSpan: 1 },
      { col: 4, row: 1, colSpan: 1, rowSpan: 1 },
    ],
  },

  // ---- 6 photos ----
  {
    key: 'grid-6-normal',
    label: '6 fotos',
    count: 6,
    cols: 3,
    rows: 2,
    cells: [
      { col: 0, row: 0, colSpan: 1, rowSpan: 1 },
      { col: 1, row: 0, colSpan: 1, rowSpan: 1 },
      { col: 2, row: 0, colSpan: 1, rowSpan: 1 },
      { col: 0, row: 1, colSpan: 1, rowSpan: 1 },
      { col: 1, row: 1, colSpan: 1, rowSpan: 1 },
      { col: 2, row: 1, colSpan: 1, rowSpan: 1 },
    ],
  },
  {
    key: 'grid-6-pairs',
    label: '6 fotos · 3 filas dobles',
    count: 6,
    cols: 4,
    rows: 3,
    cells: [
      { col: 0, row: 0, colSpan: 2, rowSpan: 1 },
      { col: 2, row: 0, colSpan: 2, rowSpan: 1 },
      { col: 0, row: 1, colSpan: 2, rowSpan: 1 },
      { col: 2, row: 1, colSpan: 2, rowSpan: 1 },
      { col: 0, row: 2, colSpan: 2, rowSpan: 1 },
      { col: 2, row: 2, colSpan: 2, rowSpan: 1 },
    ],
  },
  {
    key: 'grid-6-big',
    label: '6 fotos · grande + 5',
    count: 6,
    cols: 4,
    rows: 3,
    cells: [
      { col: 0, row: 0, colSpan: 2, rowSpan: 2 },
      { col: 2, row: 0, colSpan: 1, rowSpan: 1 },
      { col: 3, row: 0, colSpan: 1, rowSpan: 1 },
      { col: 2, row: 1, colSpan: 1, rowSpan: 1 },
      { col: 3, row: 1, colSpan: 1, rowSpan: 1 },
      { col: 0, row: 2, colSpan: 4, rowSpan: 1 },
    ],
  },
  {
    key: 'grid-6-row',
    label: '6 fotos · en fila',
    count: 6,
    cols: 6,
    rows: 1,
    cells: [
      { col: 0, row: 0, colSpan: 1, rowSpan: 1 },
      { col: 1, row: 0, colSpan: 1, rowSpan: 1 },
      { col: 2, row: 0, colSpan: 1, rowSpan: 1 },
      { col: 3, row: 0, colSpan: 1, rowSpan: 1 },
      { col: 4, row: 0, colSpan: 1, rowSpan: 1 },
      { col: 5, row: 0, colSpan: 1, rowSpan: 1 },
    ],
  },

  {
    key: 'grid-6-band-panel-trio',
    label: '6 fotos · panel + franjas + trío',
    count: 6,
    cols: 6,
    rows: 3,
    cells: [
      { col: 0, row: 0, colSpan: 3, rowSpan: 1 },
      { col: 3, row: 0, colSpan: 3, rowSpan: 2 },
      { col: 0, row: 1, colSpan: 3, rowSpan: 1 },
      { col: 0, row: 2, colSpan: 2, rowSpan: 1 },
      { col: 2, row: 2, colSpan: 2, rowSpan: 1 },
      { col: 4, row: 2, colSpan: 2, rowSpan: 1 },
    ],
  },
  {
    key: 'grid-6-trio-tall-split',
    label: '6 fotos · trío + alta + dividido',
    count: 6,
    cols: 4,
    rows: 2,
    cells: [
      { col: 0, row: 0, colSpan: 1, rowSpan: 1 },
      { col: 1, row: 0, colSpan: 1, rowSpan: 1 },
      { col: 2, row: 0, colSpan: 1, rowSpan: 1 },
      { col: 3, row: 0, colSpan: 1, rowSpan: 2 },
      { col: 0, row: 1, colSpan: 2, rowSpan: 1 },
      { col: 2, row: 1, colSpan: 1, rowSpan: 1 },
    ],
  },
  {
    key: 'grid-6-stack-tall-band',
    label: '6 fotos · apiladas + alta + franja',
    count: 6,
    cols: 2,
    rows: 5,
    cells: [
      { col: 0, row: 0, colSpan: 1, rowSpan: 1 },
      { col: 1, row: 0, colSpan: 1, rowSpan: 4 },
      { col: 0, row: 1, colSpan: 1, rowSpan: 1 },
      { col: 0, row: 2, colSpan: 1, rowSpan: 1 },
      { col: 0, row: 3, colSpan: 1, rowSpan: 1 },
      { col: 0, row: 4, colSpan: 2, rowSpan: 1 },
    ],
  },
  {
    key: 'grid-6-mixed-band-a',
    label: '6 fotos · mosaico + franja A',
    count: 6,
    cols: 2,
    rows: 4,
    cells: [
      { col: 0, row: 0, colSpan: 1, rowSpan: 1 },
      { col: 1, row: 0, colSpan: 1, rowSpan: 1 },
      { col: 0, row: 1, colSpan: 1, rowSpan: 2 },
      { col: 1, row: 1, colSpan: 1, rowSpan: 1 },
      { col: 1, row: 2, colSpan: 1, rowSpan: 1 },
      { col: 0, row: 3, colSpan: 2, rowSpan: 1 },
    ],
  },
  {
    key: 'grid-6-two-tall-stack',
    label: '6 fotos · 2 altas + 4 apiladas',
    count: 6,
    cols: 2,
    rows: 4,
    cells: [
      { col: 0, row: 0, colSpan: 1, rowSpan: 2 },
      { col: 1, row: 0, colSpan: 1, rowSpan: 1 },
      { col: 1, row: 1, colSpan: 1, rowSpan: 1 },
      { col: 0, row: 2, colSpan: 1, rowSpan: 2 },
      { col: 1, row: 2, colSpan: 1, rowSpan: 1 },
      { col: 1, row: 3, colSpan: 1, rowSpan: 1 },
    ],
  },
  {
    key: 'grid-6-cols-asym',
    label: '6 fotos · columnas asimétricas',
    count: 6,
    cols: 3,
    rows: 3,
    cells: [
      { col: 0, row: 0, colSpan: 1, rowSpan: 1 },
      { col: 1, row: 0, colSpan: 1, rowSpan: 2 },
      { col: 2, row: 0, colSpan: 1, rowSpan: 3 },
      { col: 0, row: 1, colSpan: 1, rowSpan: 1 },
      { col: 1, row: 2, colSpan: 1, rowSpan: 1 },
      { col: 0, row: 2, colSpan: 1, rowSpan: 1 },
    ],
  },
  {
    key: 'grid-6-stack-tall-top',
    label: '6 fotos · apiladas + alta arriba',
    count: 6,
    cols: 2,
    rows: 4,
    cells: [
      { col: 0, row: 0, colSpan: 1, rowSpan: 1 },
      { col: 1, row: 0, colSpan: 1, rowSpan: 1 },
      { col: 0, row: 1, colSpan: 1, rowSpan: 1 },
      { col: 1, row: 1, colSpan: 1, rowSpan: 3 },
      { col: 0, row: 2, colSpan: 1, rowSpan: 1 },
      { col: 0, row: 3, colSpan: 1, rowSpan: 1 },
    ],
  },
  {
    key: 'grid-6-stack-tall-bottom',
    label: '6 fotos · apiladas + alta abajo',
    count: 6,
    cols: 2,
    rows: 4,
    cells: [
      { col: 0, row: 0, colSpan: 1, rowSpan: 1 },
      { col: 1, row: 0, colSpan: 1, rowSpan: 3 },
      { col: 0, row: 1, colSpan: 1, rowSpan: 1 },
      { col: 0, row: 2, colSpan: 1, rowSpan: 1 },
      { col: 0, row: 3, colSpan: 1, rowSpan: 1 },
      { col: 1, row: 3, colSpan: 1, rowSpan: 1 },
    ],
  },
  {
    key: 'grid-6-tall-stack-plain',
    label: '6 fotos · columna alta + 5 filas',
    count: 6,
    cols: 2,
    rows: 5,
    cells: [
      { col: 0, row: 0, colSpan: 1, rowSpan: 5 },
      { col: 1, row: 0, colSpan: 1, rowSpan: 1 },
      { col: 1, row: 1, colSpan: 1, rowSpan: 1 },
      { col: 1, row: 2, colSpan: 1, rowSpan: 1 },
      { col: 1, row: 3, colSpan: 1, rowSpan: 1 },
      { col: 1, row: 4, colSpan: 1, rowSpan: 1 },
    ],
  },
  {
    key: 'grid-6-stack-panel-band',
    label: '6 fotos · apiladas + panel + franja',
    count: 6,
    cols: 3,
    rows: 4,
    cells: [
      { col: 0, row: 0, colSpan: 1, rowSpan: 1 },
      { col: 0, row: 1, colSpan: 1, rowSpan: 1 },
      { col: 0, row: 2, colSpan: 1, rowSpan: 1 },
      { col: 0, row: 3, colSpan: 1, rowSpan: 1 },
      { col: 1, row: 0, colSpan: 2, rowSpan: 3 },
      { col: 1, row: 3, colSpan: 2, rowSpan: 1 },
    ],
  },
  {
    key: 'grid-6-mosaic-band',
    label: '6 fotos · mosaico + franja inferior',
    count: 6,
    cols: 3,
    rows: 10,
    cells: [
      { col: 0, row: 0, colSpan: 1, rowSpan: 2 },
      { col: 1, row: 0, colSpan: 1, rowSpan: 2 },
      { col: 2, row: 0, colSpan: 1, rowSpan: 5 },
      { col: 0, row: 2, colSpan: 1, rowSpan: 3 },
      { col: 1, row: 2, colSpan: 1, rowSpan: 3 },
      { col: 0, row: 5, colSpan: 3, rowSpan: 5 },
    ],
  },
  {
    key: 'grid-6-bands-pairs',
    label: '6 fotos · franjas + 2 pares',
    count: 6,
    cols: 2,
    rows: 10,
    cells: [
      { col: 0, row: 0, colSpan: 2, rowSpan: 2 },
      { col: 0, row: 2, colSpan: 1, rowSpan: 3 },
      { col: 1, row: 2, colSpan: 1, rowSpan: 3 },
      { col: 0, row: 5, colSpan: 1, rowSpan: 3 },
      { col: 1, row: 5, colSpan: 1, rowSpan: 3 },
      { col: 0, row: 8, colSpan: 2, rowSpan: 2 },
    ],
  },
  {
    key: 'grid-6-stack-panel',
    label: '6 fotos · columna + panel grande',
    count: 6,
    cols: 3,
    rows: 5,
    cells: [
      { col: 0, row: 0, colSpan: 1, rowSpan: 1 },
      { col: 0, row: 1, colSpan: 1, rowSpan: 1 },
      { col: 0, row: 2, colSpan: 1, rowSpan: 1 },
      { col: 0, row: 3, colSpan: 1, rowSpan: 1 },
      { col: 0, row: 4, colSpan: 1, rowSpan: 1 },
      { col: 1, row: 0, colSpan: 2, rowSpan: 5 },
    ],
  },

  // ---- 7 photos ----
  {
    key: 'grid-7-normal',
    label: '7 fotos',
    count: 7,
    cols: 4,
    rows: 2,
    cells: [
      { col: 0, row: 0, colSpan: 1, rowSpan: 1 },
      { col: 1, row: 0, colSpan: 1, rowSpan: 1 },
      { col: 2, row: 0, colSpan: 1, rowSpan: 1 },
      { col: 3, row: 0, colSpan: 1, rowSpan: 1 },
      { col: 0, row: 1, colSpan: 1, rowSpan: 1 },
      { col: 1, row: 1, colSpan: 1, rowSpan: 1 },
      { col: 2, row: 1, colSpan: 2, rowSpan: 1 },
    ],
  },
  {
    key: 'grid-7-big-top',
    label: '7 fotos · grande arriba',
    count: 7,
    cols: 4,
    rows: 2,
    cells: [
      { col: 0, row: 0, colSpan: 2, rowSpan: 1 },
      { col: 2, row: 0, colSpan: 1, rowSpan: 1 },
      { col: 3, row: 0, colSpan: 1, rowSpan: 1 },
      { col: 0, row: 1, colSpan: 1, rowSpan: 1 },
      { col: 1, row: 1, colSpan: 1, rowSpan: 1 },
      { col: 2, row: 1, colSpan: 1, rowSpan: 1 },
      { col: 3, row: 1, colSpan: 1, rowSpan: 1 },
    ],
  },
  {
    key: 'grid-7-big-bottom',
    label: '7 fotos · grande abajo',
    count: 7,
    cols: 4,
    rows: 2,
    cells: [
      { col: 0, row: 0, colSpan: 1, rowSpan: 1 },
      { col: 1, row: 0, colSpan: 1, rowSpan: 1 },
      { col: 2, row: 0, colSpan: 1, rowSpan: 1 },
      { col: 3, row: 0, colSpan: 1, rowSpan: 1 },
      { col: 0, row: 1, colSpan: 2, rowSpan: 1 },
      { col: 2, row: 1, colSpan: 1, rowSpan: 1 },
      { col: 3, row: 1, colSpan: 1, rowSpan: 1 },
    ],
  },
  {
    // A 3x3 grid with the center and top-middle left open — a "U" of 7 cells.
    key: 'grid-7-horseshoe',
    label: '7 fotos · herradura',
    count: 7,
    cols: 3,
    rows: 3,
    cells: [
      { col: 0, row: 0, colSpan: 1, rowSpan: 1 },
      { col: 2, row: 0, colSpan: 1, rowSpan: 1 },
      { col: 0, row: 1, colSpan: 1, rowSpan: 1 },
      { col: 2, row: 1, colSpan: 1, rowSpan: 1 },
      { col: 0, row: 2, colSpan: 1, rowSpan: 1 },
      { col: 1, row: 2, colSpan: 1, rowSpan: 1 },
      { col: 2, row: 2, colSpan: 1, rowSpan: 1 },
    ],
  },

  {
    key: 'grid-7-mosaic',
    label: '7 fotos · mosaico asimétrico',
    count: 7,
    cols: 3,
    rows: 3,
    cells: [
      { col: 0, row: 0, colSpan: 1, rowSpan: 1 },
      { col: 1, row: 0, colSpan: 1, rowSpan: 1 },
      { col: 2, row: 0, colSpan: 1, rowSpan: 2 },
      { col: 0, row: 1, colSpan: 1, rowSpan: 1 },
      { col: 1, row: 1, colSpan: 1, rowSpan: 1 },
      { col: 0, row: 2, colSpan: 1, rowSpan: 1 },
      { col: 1, row: 2, colSpan: 2, rowSpan: 1 },
    ],
  },
  {
    key: 'grid-7-stack-panel-split',
    label: '7 fotos · columna + panel dividido',
    count: 7,
    cols: 3,
    rows: 5,
    cells: [
      { col: 0, row: 0, colSpan: 1, rowSpan: 1 },
      { col: 0, row: 1, colSpan: 1, rowSpan: 1 },
      { col: 0, row: 2, colSpan: 1, rowSpan: 1 },
      { col: 0, row: 3, colSpan: 1, rowSpan: 1 },
      { col: 0, row: 4, colSpan: 1, rowSpan: 1 },
      { col: 1, row: 0, colSpan: 2, rowSpan: 3 },
      { col: 1, row: 3, colSpan: 2, rowSpan: 2 },
    ],
  },
  {
    key: 'grid-7-mosaic-complex',
    label: '7 fotos · mosaico complejo',
    count: 7,
    cols: 6,
    rows: 6,
    cells: [
      { col: 0, row: 0, colSpan: 3, rowSpan: 2 },
      { col: 3, row: 0, colSpan: 3, rowSpan: 3 },
      { col: 0, row: 2, colSpan: 3, rowSpan: 2 },
      { col: 3, row: 3, colSpan: 3, rowSpan: 1 },
      { col: 0, row: 4, colSpan: 2, rowSpan: 2 },
      { col: 2, row: 4, colSpan: 2, rowSpan: 2 },
      { col: 4, row: 4, colSpan: 2, rowSpan: 2 },
    ],
  },
  {
    key: 'grid-7-row',
    label: '7 fotos · en fila',
    count: 7,
    cols: 7,
    rows: 1,
    cells: [
      { col: 0, row: 0, colSpan: 1, rowSpan: 1 },
      { col: 1, row: 0, colSpan: 1, rowSpan: 1 },
      { col: 2, row: 0, colSpan: 1, rowSpan: 1 },
      { col: 3, row: 0, colSpan: 1, rowSpan: 1 },
      { col: 4, row: 0, colSpan: 1, rowSpan: 1 },
      { col: 5, row: 0, colSpan: 1, rowSpan: 1 },
      { col: 6, row: 0, colSpan: 1, rowSpan: 1 },
    ],
  },
  {
    key: 'grid-7-hero-strip',
    label: '7 fotos · protagonista + tira inferior',
    count: 7,
    cols: 6,
    rows: 5,
    cells: [
      { col: 0, row: 0, colSpan: 6, rowSpan: 3 },
      { col: 0, row: 3, colSpan: 1, rowSpan: 2 },
      { col: 1, row: 3, colSpan: 1, rowSpan: 2 },
      { col: 2, row: 3, colSpan: 1, rowSpan: 2 },
      { col: 3, row: 3, colSpan: 1, rowSpan: 2 },
      { col: 4, row: 3, colSpan: 1, rowSpan: 2 },
      { col: 5, row: 3, colSpan: 1, rowSpan: 2 },
    ],
  },
  {
    key: 'grid-7-banner-grid',
    label: '7 fotos · franja + cuadrícula 3x2',
    count: 7,
    cols: 6,
    rows: 3,
    cells: [
      { col: 0, row: 0, colSpan: 6, rowSpan: 1 },
      { col: 0, row: 1, colSpan: 2, rowSpan: 1 },
      { col: 2, row: 1, colSpan: 2, rowSpan: 1 },
      { col: 4, row: 1, colSpan: 2, rowSpan: 1 },
      { col: 0, row: 2, colSpan: 2, rowSpan: 1 },
      { col: 2, row: 2, colSpan: 2, rowSpan: 1 },
      { col: 4, row: 2, colSpan: 2, rowSpan: 1 },
    ],
  },
  {
    // Deliberate negative space: a thick L (top row + left column) on a 4x4
    // grid leaves a 3x3 block intentionally empty — a larger-scale corner
    // accent than the existing 3x3 "horseshoe" (a ring, not a block).
    key: 'grid-7-corner-l',
    label: '7 fotos · esquina en L',
    count: 7,
    cols: 4,
    rows: 4,
    cells: [
      { col: 0, row: 0, colSpan: 1, rowSpan: 1 },
      { col: 1, row: 0, colSpan: 1, rowSpan: 1 },
      { col: 2, row: 0, colSpan: 1, rowSpan: 1 },
      { col: 3, row: 0, colSpan: 1, rowSpan: 1 },
      { col: 0, row: 1, colSpan: 1, rowSpan: 1 },
      { col: 0, row: 2, colSpan: 1, rowSpan: 1 },
      { col: 0, row: 3, colSpan: 1, rowSpan: 1 },
    ],
  },
  {
    key: 'grid-7-mixed-mosaic',
    label: '7 fotos · mosaico mixto',
    count: 7,
    cols: 5,
    rows: 3,
    cells: [
      { col: 0, row: 0, colSpan: 2, rowSpan: 2 },
      { col: 2, row: 0, colSpan: 2, rowSpan: 1 },
      { col: 4, row: 0, colSpan: 1, rowSpan: 2 },
      { col: 2, row: 1, colSpan: 1, rowSpan: 1 },
      { col: 3, row: 1, colSpan: 1, rowSpan: 1 },
      { col: 0, row: 2, colSpan: 3, rowSpan: 1 },
      { col: 3, row: 2, colSpan: 2, rowSpan: 1 },
    ],
  },

  // ---- 8 photos ----
  {
    key: 'grid-8-normal',
    label: '8 fotos',
    count: 8,
    cols: 4,
    rows: 2,
    cells: [
      { col: 0, row: 0, colSpan: 1, rowSpan: 1 },
      { col: 1, row: 0, colSpan: 1, rowSpan: 1 },
      { col: 2, row: 0, colSpan: 1, rowSpan: 1 },
      { col: 3, row: 0, colSpan: 1, rowSpan: 1 },
      { col: 0, row: 1, colSpan: 1, rowSpan: 1 },
      { col: 1, row: 1, colSpan: 1, rowSpan: 1 },
      { col: 2, row: 1, colSpan: 1, rowSpan: 1 },
      { col: 3, row: 1, colSpan: 1, rowSpan: 1 },
    ],
  },
  {
    key: 'grid-8-big',
    label: '8 fotos · grande + 7',
    count: 8,
    cols: 4,
    rows: 3,
    cells: [
      { col: 0, row: 0, colSpan: 2, rowSpan: 2 },
      { col: 2, row: 0, colSpan: 1, rowSpan: 1 },
      { col: 3, row: 0, colSpan: 1, rowSpan: 1 },
      { col: 2, row: 1, colSpan: 1, rowSpan: 1 },
      { col: 3, row: 1, colSpan: 1, rowSpan: 1 },
      { col: 0, row: 2, colSpan: 1, rowSpan: 1 },
      { col: 1, row: 2, colSpan: 1, rowSpan: 1 },
      { col: 2, row: 2, colSpan: 2, rowSpan: 1 },
    ],
  },
  {
    key: 'grid-8-row',
    label: '8 fotos · en fila',
    count: 8,
    cols: 8,
    rows: 1,
    cells: [
      { col: 0, row: 0, colSpan: 1, rowSpan: 1 },
      { col: 1, row: 0, colSpan: 1, rowSpan: 1 },
      { col: 2, row: 0, colSpan: 1, rowSpan: 1 },
      { col: 3, row: 0, colSpan: 1, rowSpan: 1 },
      { col: 4, row: 0, colSpan: 1, rowSpan: 1 },
      { col: 5, row: 0, colSpan: 1, rowSpan: 1 },
      { col: 6, row: 0, colSpan: 1, rowSpan: 1 },
      { col: 7, row: 0, colSpan: 1, rowSpan: 1 },
    ],
  },
  {
    key: 'grid-8-col',
    label: '8 fotos · 2 columnas',
    count: 8,
    cols: 2,
    rows: 4,
    cells: [
      { col: 0, row: 0, colSpan: 1, rowSpan: 1 },
      { col: 1, row: 0, colSpan: 1, rowSpan: 1 },
      { col: 0, row: 1, colSpan: 1, rowSpan: 1 },
      { col: 1, row: 1, colSpan: 1, rowSpan: 1 },
      { col: 0, row: 2, colSpan: 1, rowSpan: 1 },
      { col: 1, row: 2, colSpan: 1, rowSpan: 1 },
      { col: 0, row: 3, colSpan: 1, rowSpan: 1 },
      { col: 1, row: 3, colSpan: 1, rowSpan: 1 },
    ],
  },
  {
    key: 'grid-8-double-band-cols',
    label: '8 fotos · doble franja + 4 columnas',
    count: 8,
    cols: 4,
    rows: 4,
    cells: [
      { col: 0, row: 0, colSpan: 2, rowSpan: 1 },
      { col: 2, row: 0, colSpan: 2, rowSpan: 1 },
      { col: 0, row: 1, colSpan: 1, rowSpan: 2 },
      { col: 1, row: 1, colSpan: 1, rowSpan: 2 },
      { col: 2, row: 1, colSpan: 1, rowSpan: 2 },
      { col: 3, row: 1, colSpan: 1, rowSpan: 2 },
      { col: 0, row: 3, colSpan: 2, rowSpan: 1 },
      { col: 2, row: 3, colSpan: 2, rowSpan: 1 },
    ],
  },
  {
    key: 'grid-8-banner-strip',
    label: '8 fotos · banner + tira de 7',
    count: 8,
    cols: 7,
    rows: 3,
    cells: [
      { col: 0, row: 0, colSpan: 7, rowSpan: 1 },
      { col: 0, row: 1, colSpan: 1, rowSpan: 2 },
      { col: 1, row: 1, colSpan: 1, rowSpan: 2 },
      { col: 2, row: 1, colSpan: 1, rowSpan: 2 },
      { col: 3, row: 1, colSpan: 1, rowSpan: 2 },
      { col: 4, row: 1, colSpan: 1, rowSpan: 2 },
      { col: 5, row: 1, colSpan: 1, rowSpan: 2 },
      { col: 6, row: 1, colSpan: 1, rowSpan: 2 },
    ],
  },
  {
    key: 'grid-8-tall-col-mosaic',
    label: '8 fotos · columna alta + mosaico',
    count: 8,
    cols: 5,
    rows: 4,
    cells: [
      { col: 0, row: 0, colSpan: 2, rowSpan: 4 },
      { col: 2, row: 0, colSpan: 1, rowSpan: 2 },
      { col: 3, row: 0, colSpan: 1, rowSpan: 2 },
      { col: 4, row: 0, colSpan: 1, rowSpan: 2 },
      { col: 2, row: 2, colSpan: 1, rowSpan: 1 },
      { col: 3, row: 2, colSpan: 1, rowSpan: 1 },
      { col: 4, row: 2, colSpan: 1, rowSpan: 1 },
      { col: 2, row: 3, colSpan: 3, rowSpan: 1 },
    ],
  },
  {
    key: 'grid-8-bands-split-center',
    label: '8 fotos · franjas con centro dividido',
    count: 8,
    cols: 4,
    rows: 3,
    cells: [
      { col: 0, row: 0, colSpan: 1, rowSpan: 1 },
      { col: 1, row: 0, colSpan: 2, rowSpan: 1 },
      { col: 3, row: 0, colSpan: 1, rowSpan: 1 },
      { col: 0, row: 1, colSpan: 2, rowSpan: 1 },
      { col: 2, row: 1, colSpan: 2, rowSpan: 1 },
      { col: 0, row: 2, colSpan: 1, rowSpan: 1 },
      { col: 1, row: 2, colSpan: 2, rowSpan: 1 },
      { col: 3, row: 2, colSpan: 1, rowSpan: 1 },
    ],
  },
  {
    key: 'grid-8-mosaic-asym',
    label: '8 fotos · mosaico asimétrico',
    count: 8,
    cols: 6,
    rows: 4,
    cells: [
      { col: 0, row: 0, colSpan: 3, rowSpan: 2 },
      { col: 3, row: 0, colSpan: 3, rowSpan: 1 },
      { col: 3, row: 1, colSpan: 2, rowSpan: 1 },
      { col: 5, row: 1, colSpan: 1, rowSpan: 1 },
      { col: 0, row: 2, colSpan: 2, rowSpan: 2 },
      { col: 2, row: 2, colSpan: 2, rowSpan: 1 },
      { col: 2, row: 3, colSpan: 2, rowSpan: 1 },
      { col: 4, row: 2, colSpan: 2, rowSpan: 2 },
    ],
  },
  {
    key: 'grid-8-frame-center',
    label: '8 fotos · marco con centro grande',
    count: 8,
    cols: 4,
    rows: 4,
    cells: [
      { col: 1, row: 1, colSpan: 2, rowSpan: 2 },
      { col: 0, row: 0, colSpan: 2, rowSpan: 1 },
      { col: 2, row: 0, colSpan: 2, rowSpan: 1 },
      { col: 0, row: 3, colSpan: 2, rowSpan: 1 },
      { col: 2, row: 3, colSpan: 2, rowSpan: 1 },
      { col: 0, row: 1, colSpan: 1, rowSpan: 1 },
      { col: 0, row: 2, colSpan: 1, rowSpan: 1 },
      { col: 3, row: 1, colSpan: 1, rowSpan: 2 },
    ],
  },
  {
    key: 'grid-8-brick-5-3',
    label: '8 fotos · ladrillo 5+3',
    count: 8,
    cols: 15,
    rows: 2,
    cells: [
      { col: 0, row: 0, colSpan: 3, rowSpan: 1 },
      { col: 3, row: 0, colSpan: 3, rowSpan: 1 },
      { col: 6, row: 0, colSpan: 3, rowSpan: 1 },
      { col: 9, row: 0, colSpan: 3, rowSpan: 1 },
      { col: 12, row: 0, colSpan: 3, rowSpan: 1 },
      { col: 0, row: 1, colSpan: 5, rowSpan: 1 },
      { col: 5, row: 1, colSpan: 5, rowSpan: 1 },
      { col: 10, row: 1, colSpan: 5, rowSpan: 1 },
    ],
  },
  {
    key: 'grid-8-cols-variable',
    label: '8 fotos · columnas con divisiones variables',
    count: 8,
    cols: 3,
    rows: 6,
    cells: [
      { col: 0, row: 0, colSpan: 1, rowSpan: 2 },
      { col: 0, row: 2, colSpan: 1, rowSpan: 2 },
      { col: 0, row: 4, colSpan: 1, rowSpan: 2 },
      { col: 1, row: 0, colSpan: 1, rowSpan: 3 },
      { col: 1, row: 3, colSpan: 1, rowSpan: 3 },
      { col: 2, row: 0, colSpan: 1, rowSpan: 2 },
      { col: 2, row: 2, colSpan: 1, rowSpan: 2 },
      { col: 2, row: 4, colSpan: 1, rowSpan: 2 },
    ],
  },
  {
    key: 'grid-8-base-mosaic',
    label: '8 fotos · base grande + mosaico superior',
    count: 8,
    cols: 6,
    rows: 4,
    cells: [
      { col: 0, row: 2, colSpan: 6, rowSpan: 2 },
      { col: 0, row: 0, colSpan: 2, rowSpan: 1 },
      { col: 2, row: 0, colSpan: 2, rowSpan: 1 },
      { col: 4, row: 0, colSpan: 2, rowSpan: 1 },
      { col: 0, row: 1, colSpan: 2, rowSpan: 1 },
      { col: 2, row: 1, colSpan: 2, rowSpan: 1 },
      { col: 4, row: 1, colSpan: 1, rowSpan: 1 },
      { col: 5, row: 1, colSpan: 1, rowSpan: 1 },
    ],
  },

  // ---- 9 photos ----
  {
    key: 'grid-9-normal',
    label: '9 fotos',
    count: 9,
    cols: 3,
    rows: 3,
    cells: [
      { col: 0, row: 0, colSpan: 1, rowSpan: 1 },
      { col: 1, row: 0, colSpan: 1, rowSpan: 1 },
      { col: 2, row: 0, colSpan: 1, rowSpan: 1 },
      { col: 0, row: 1, colSpan: 1, rowSpan: 1 },
      { col: 1, row: 1, colSpan: 1, rowSpan: 1 },
      { col: 2, row: 1, colSpan: 1, rowSpan: 1 },
      { col: 0, row: 2, colSpan: 1, rowSpan: 1 },
      { col: 1, row: 2, colSpan: 1, rowSpan: 1 },
      { col: 2, row: 2, colSpan: 1, rowSpan: 1 },
    ],
  },
  {
    key: 'grid-9-big',
    label: '9 fotos · grande + 8',
    count: 9,
    cols: 4,
    rows: 3,
    cells: [
      { col: 0, row: 0, colSpan: 2, rowSpan: 2 },
      { col: 2, row: 0, colSpan: 1, rowSpan: 1 },
      { col: 3, row: 0, colSpan: 1, rowSpan: 1 },
      { col: 2, row: 1, colSpan: 1, rowSpan: 1 },
      { col: 3, row: 1, colSpan: 1, rowSpan: 1 },
      { col: 0, row: 2, colSpan: 1, rowSpan: 1 },
      { col: 1, row: 2, colSpan: 1, rowSpan: 1 },
      { col: 2, row: 2, colSpan: 1, rowSpan: 1 },
      { col: 3, row: 2, colSpan: 1, rowSpan: 1 },
    ],
  },
  {
    key: 'grid-9-row',
    label: '9 fotos · en fila',
    count: 9,
    cols: 9,
    rows: 1,
    cells: [
      { col: 0, row: 0, colSpan: 1, rowSpan: 1 },
      { col: 1, row: 0, colSpan: 1, rowSpan: 1 },
      { col: 2, row: 0, colSpan: 1, rowSpan: 1 },
      { col: 3, row: 0, colSpan: 1, rowSpan: 1 },
      { col: 4, row: 0, colSpan: 1, rowSpan: 1 },
      { col: 5, row: 0, colSpan: 1, rowSpan: 1 },
      { col: 6, row: 0, colSpan: 1, rowSpan: 1 },
      { col: 7, row: 0, colSpan: 1, rowSpan: 1 },
      { col: 8, row: 0, colSpan: 1, rowSpan: 1 },
    ],
  },
  {
    key: 'grid-9-col',
    label: '9 fotos · en columna',
    count: 9,
    cols: 1,
    rows: 9,
    cells: [
      { col: 0, row: 0, colSpan: 1, rowSpan: 1 },
      { col: 0, row: 1, colSpan: 1, rowSpan: 1 },
      { col: 0, row: 2, colSpan: 1, rowSpan: 1 },
      { col: 0, row: 3, colSpan: 1, rowSpan: 1 },
      { col: 0, row: 4, colSpan: 1, rowSpan: 1 },
      { col: 0, row: 5, colSpan: 1, rowSpan: 1 },
      { col: 0, row: 6, colSpan: 1, rowSpan: 1 },
      { col: 0, row: 7, colSpan: 1, rowSpan: 1 },
      { col: 0, row: 8, colSpan: 1, rowSpan: 1 },
    ],
  },
  {
    key: 'grid-9-frame-center',
    label: '9 fotos · marco con centro grande',
    count: 9,
    cols: 5,
    rows: 5,
    cells: [
      { col: 1, row: 1, colSpan: 3, rowSpan: 3 },
      { col: 0, row: 0, colSpan: 1, rowSpan: 1 },
      { col: 1, row: 0, colSpan: 3, rowSpan: 1 },
      { col: 4, row: 0, colSpan: 1, rowSpan: 1 },
      { col: 0, row: 4, colSpan: 1, rowSpan: 1 },
      { col: 1, row: 4, colSpan: 3, rowSpan: 1 },
      { col: 4, row: 4, colSpan: 1, rowSpan: 1 },
      { col: 0, row: 1, colSpan: 1, rowSpan: 3 },
      { col: 4, row: 1, colSpan: 1, rowSpan: 3 },
    ],
  },
  {
    key: 'grid-9-banner-grid',
    label: '9 fotos · banner + cuadrícula 4x2',
    count: 9,
    cols: 4,
    rows: 3,
    cells: [
      { col: 0, row: 0, colSpan: 4, rowSpan: 1 },
      { col: 0, row: 1, colSpan: 1, rowSpan: 1 },
      { col: 1, row: 1, colSpan: 1, rowSpan: 1 },
      { col: 2, row: 1, colSpan: 1, rowSpan: 1 },
      { col: 3, row: 1, colSpan: 1, rowSpan: 1 },
      { col: 0, row: 2, colSpan: 1, rowSpan: 1 },
      { col: 1, row: 2, colSpan: 1, rowSpan: 1 },
      { col: 2, row: 2, colSpan: 1, rowSpan: 1 },
      { col: 3, row: 2, colSpan: 1, rowSpan: 1 },
    ],
  },
  {
    key: 'grid-9-big-bottom-mosaic',
    label: '9 fotos · grande inferior + mosaico',
    count: 9,
    cols: 5,
    rows: 3,
    cells: [
      { col: 2, row: 1, colSpan: 3, rowSpan: 2 },
      { col: 0, row: 0, colSpan: 1, rowSpan: 1 },
      { col: 1, row: 0, colSpan: 1, rowSpan: 1 },
      { col: 2, row: 0, colSpan: 1, rowSpan: 1 },
      { col: 3, row: 0, colSpan: 1, rowSpan: 1 },
      { col: 4, row: 0, colSpan: 1, rowSpan: 1 },
      { col: 0, row: 1, colSpan: 1, rowSpan: 2 },
      { col: 1, row: 1, colSpan: 1, rowSpan: 1 },
      { col: 1, row: 2, colSpan: 1, rowSpan: 1 },
    ],
  },
  {
    key: 'grid-9-mosaic-asym',
    label: '9 fotos · mosaico asimétrico',
    count: 9,
    cols: 6,
    rows: 4,
    cells: [
      { col: 0, row: 0, colSpan: 3, rowSpan: 2 },
      { col: 3, row: 0, colSpan: 3, rowSpan: 1 },
      { col: 3, row: 1, colSpan: 1, rowSpan: 1 },
      { col: 4, row: 1, colSpan: 1, rowSpan: 1 },
      { col: 5, row: 1, colSpan: 1, rowSpan: 1 },
      { col: 0, row: 2, colSpan: 2, rowSpan: 2 },
      { col: 2, row: 2, colSpan: 2, rowSpan: 1 },
      { col: 2, row: 3, colSpan: 2, rowSpan: 1 },
      { col: 4, row: 2, colSpan: 2, rowSpan: 2 },
    ],
  },
  {
    key: 'grid-9-brick-5-4',
    label: '9 fotos · ladrillo 5+4',
    count: 9,
    cols: 20,
    rows: 2,
    cells: [
      { col: 0, row: 0, colSpan: 4, rowSpan: 1 },
      { col: 4, row: 0, colSpan: 4, rowSpan: 1 },
      { col: 8, row: 0, colSpan: 4, rowSpan: 1 },
      { col: 12, row: 0, colSpan: 4, rowSpan: 1 },
      { col: 16, row: 0, colSpan: 4, rowSpan: 1 },
      { col: 0, row: 1, colSpan: 5, rowSpan: 1 },
      { col: 5, row: 1, colSpan: 5, rowSpan: 1 },
      { col: 10, row: 1, colSpan: 5, rowSpan: 1 },
      { col: 15, row: 1, colSpan: 5, rowSpan: 1 },
    ],
  },
  {
    key: 'grid-9-cols-variable',
    label: '9 fotos · columnas con divisiones variables',
    count: 9,
    cols: 3,
    rows: 12,
    cells: [
      { col: 0, row: 0, colSpan: 1, rowSpan: 6 },
      { col: 0, row: 6, colSpan: 1, rowSpan: 6 },
      { col: 1, row: 0, colSpan: 1, rowSpan: 4 },
      { col: 1, row: 4, colSpan: 1, rowSpan: 4 },
      { col: 1, row: 8, colSpan: 1, rowSpan: 4 },
      { col: 2, row: 0, colSpan: 1, rowSpan: 3 },
      { col: 2, row: 3, colSpan: 1, rowSpan: 3 },
      { col: 2, row: 6, colSpan: 1, rowSpan: 3 },
      { col: 2, row: 9, colSpan: 1, rowSpan: 3 },
    ],
  },
  {
    key: 'grid-9-big-strip-bands',
    label: '9 fotos · grande + tira + franjas',
    count: 9,
    cols: 5,
    rows: 5,
    cells: [
      { col: 0, row: 0, colSpan: 3, rowSpan: 3 },
      { col: 3, row: 0, colSpan: 1, rowSpan: 1 },
      { col: 4, row: 0, colSpan: 1, rowSpan: 1 },
      { col: 3, row: 1, colSpan: 1, rowSpan: 1 },
      { col: 4, row: 1, colSpan: 1, rowSpan: 1 },
      { col: 3, row: 2, colSpan: 1, rowSpan: 1 },
      { col: 4, row: 2, colSpan: 1, rowSpan: 1 },
      { col: 0, row: 3, colSpan: 5, rowSpan: 1 },
      { col: 0, row: 4, colSpan: 5, rowSpan: 1 },
    ],
  },
  {
    key: 'grid-9-double-hero-mosaic',
    label: '9 fotos · doble protagonista + mosaico',
    count: 9,
    cols: 6,
    rows: 4,
    cells: [
      { col: 0, row: 0, colSpan: 2, rowSpan: 2 },
      { col: 4, row: 2, colSpan: 2, rowSpan: 2 },
      { col: 2, row: 0, colSpan: 4, rowSpan: 1 },
      { col: 2, row: 1, colSpan: 2, rowSpan: 1 },
      { col: 4, row: 1, colSpan: 2, rowSpan: 1 },
      { col: 0, row: 2, colSpan: 1, rowSpan: 2 },
      { col: 1, row: 2, colSpan: 1, rowSpan: 2 },
      { col: 2, row: 2, colSpan: 1, rowSpan: 2 },
      { col: 3, row: 2, colSpan: 1, rowSpan: 2 },
    ],
  },
  {
    key: 'grid-9-center-col-mosaics',
    label: '9 fotos · columna central + mosaicos laterales',
    count: 9,
    cols: 6,
    rows: 4,
    cells: [
      { col: 2, row: 0, colSpan: 2, rowSpan: 4 },
      { col: 0, row: 0, colSpan: 1, rowSpan: 2 },
      { col: 1, row: 0, colSpan: 1, rowSpan: 2 },
      { col: 0, row: 2, colSpan: 1, rowSpan: 2 },
      { col: 1, row: 2, colSpan: 1, rowSpan: 2 },
      { col: 4, row: 0, colSpan: 2, rowSpan: 1 },
      { col: 4, row: 1, colSpan: 2, rowSpan: 1 },
      { col: 4, row: 2, colSpan: 2, rowSpan: 1 },
      { col: 4, row: 3, colSpan: 2, rowSpan: 1 },
    ],
  },
]

export const GRID_TEMPLATES: GridTemplate[] = GEOMETRIES.map((g) => ({
  id: g.key,
  label: g.label,
  count: g.count,
  cols: g.cols,
  rows: g.rows,
  cells: g.cells,
}))

export const MIN_COLLAGE_PHOTOS = 2
export const MAX_COLLAGE_PHOTOS = 9

/** All templates available for a given photo count (2-9), in a stable order. */
export function getTemplatesForCount(count: number): GridTemplate[] {
  const clamped = Math.min(MAX_COLLAGE_PHOTOS, Math.max(MIN_COLLAGE_PHOTOS, count))
  return GRID_TEMPLATES.filter((t) => t.count === clamped)
}

/** Looks up a template by id, falling back to the first template for that photo count. */
export function getTemplateById(id: string, fallbackCount: number): GridTemplate {
  return GRID_TEMPLATES.find((t) => t.id === id) ?? getTemplatesForCount(fallbackCount)[0]
}

/**
 * Mirrors a template along its diagonal: rows become columns and vice versa.
 * A simple side-by-side row (2 photos) becomes a top/bottom stack, a 3-in-a-row
 * becomes 3 stacked, etc. — works for any template since a transposed tiling is
 * still a valid tiling.
 */
export function transposeTemplate(template: GridTemplate): GridTemplate {
  return {
    ...template,
    id: `${template.id}-t`,
    cols: template.rows,
    rows: template.cols,
    cells: template.cells.map((cell) => ({
      col: cell.row,
      row: cell.col,
      colSpan: cell.rowSpan,
      rowSpan: cell.colSpan,
    })),
  }
}
